### ISSUE TITLE
lineSymmetry

### ISSUE THREAD

**Issue by mirelarusso** [oro8oro/oroboro#10]
Check lineSymmetry button, when click on it, the image remain fix with no option to work on it anymore. Thank you.

**Comment by loredanacirstea** [comment]
@mirelastautt Does it work after a browser refresh (as written in the manual)?

Process flow: click on an item -> click lineSymmetry -> refresh page -> check if result is as expected or not.

**Comment by loredanacirstea** [comment]
@mirelastautt Issue should be fixed now. Still, a refresh is needed after clicking the pointSymmetry button.
