### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by mirelarusso** [oro8oro/oroboro#5]
Please check orobo.ro. I worked yesterday such good svg and orobo.ro didn't save them properly. The same today. Some of them are incomplete.

**Comment by loredanacirstea** [comment]
Closing issue as not clear enough. 
Feel free to reopen it if more details are added, such as:
- browser console error
- detailed description of the issue:
  - what was the expected output (add a screenshot if possible)
  - what was the actual output (add a screenshot if possible)
